# Builder Image
ARG NODE_VERSION=20.13.1
FROM node:${NODE_VERSION} AS builder

WORKDIR /server

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .

RUN pnpm install
RUN pnpm prisma:generate

RUN pnpm npm run build

# Production Image
FROM node:${NODE_VERSION} AS production
WORKDIR /server

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --prod

COPY --from=builder /server ./
COPY --from=builder /server/dist ./dist

EXPOSE 8000

CMD ["npm", "run", "start:dev"]
