services:
  api:
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - arain_mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  arain_mysql_data:
